version: "3"
services:
    php-fpm:
        image: basermc1/php-fpm:latest
        ports:
            - 9010:9000
        volumes:
            - ./code:/var/www/html/
        links:
            - db
        networks:
         app_net:
            ipv4_address: 192.168.20.10
    nginx:
        image: basermc1/nginx:latest
        ports:
            - 8080:80
        expose:
            - 8080
        volumes:
            - ./code:/var/www/html/        
        links:
            - php-fpm
        networks:
         app_net:
            ipv4_address: 192.168.20.11
    db:
        image: basermc1/mysql:latest
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_DATABASE: MyDB
            MYSQL_USER: MyDB
            MYSQL_PASSWORD: mydbpassword
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - ./Mysql:/var/lib/mysql
        networks:
         app_net:
            ipv4_address: 192.168.20.12
networks:
   app_net:
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 192.168.20.0/24
volumes:
  MysqlVolume:
