route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
           - send_resolved: true
             username: 'user'
             channel: '#channel'
             api_url: 'http://localhost.com'