name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ONWER_ID: jonatan-bravo
jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set env TAG
      run: echo ::set-env name=CURR_TAG::sha-$(echo $GITHUB_SHA | cut -c 1-7) 
   
    - name: Teststep
      run: |
        ls && cat install/nginx/Dockerfile
    - name: Teststep
      run: |
        pwd
    - name: Teststep
      run: |
        pwd
    - uses: docker/build-push-action@v1
    
      with:
        tag_with_ref: true
        tags: latest,${{ env.CURR_TAG }}
        push: false
    - uses: philips-software/docker-ci-scripts@v2.2.2
      with:
       dockerfile: '12'
       image-name: 'node'
       tags: 'latest 12 12.1 12.1.4'
      env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
       DOCKER_ORGANIZATION: ${{ secrets.MY_PHP_NGINX_REPO }}

   
   