# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ONWER_ID: jonatan-bravo
jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set env TAG
      run: echo ::set-env name=CURR_TAG::sha-$(echo $GITHUB_SHA | cut -c 1-7)

    - name: Set env DEPLOY_MODE
      run: echo ::set-env name=DEPLOY_MODE::${{ secrets.DEPLOY_MODE }}
    
    - name: Set env IMAGE_NAME
      run: echo ::set-env name=IMAGE_NAME::basermc/simple-flask-web
    - uses: docker/build-push-action@v1
      with:
        tag_with_ref: true
        tags: latest,${{ env.CURR_TAG }}
        push: false
    - uses: docker/build-push-action@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: basermc1/project_geekhubs
        Dockerfile: install/nginx/Dockerfile
        tag_with_ref: true
        tag_with_sha: true
        tags: latest