on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: philips-software/docker-ci-scripts@v2.2.2
      with:
        dockerfile: 'install/nginx/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.MY_PHP_NGINX_REPO }}
        tag_with_sha: true
        tags: ${{ github.sha }}