name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  ONWER_ID: jonatan-bravo
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: docker/build-push-action@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPOSITORY }}
        tag_with_ref: true
        tag_with_sha: true
        dockerfile: ./install/nginx/Dockerfile
        tags: latest
    - uses: docker/build-push-action@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPOSITORY}}
        tag_with_ref: true
        tag_with_sha: true
        dockerfile: ./install/php-fpm
        tags: latest
    - uses: docker/build-push-action@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPOSITORY}}
        tag_with_ref: true
        tag_with_sha: true
        dockerfile: ./install/mysql
        tags: latest
  

   