name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ONWER_ID: jonatan-bravo
jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set env TAG
      run: echo ::set-env name=CURR_TAG::sha-$(echo $GITHUB_SHA | cut -c 1-7) 
    - uses: docker/build-push-action@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        dockerfile: 'install/nginx/Dockerfile'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.MY_PHP_NGINX_REPO }}
        tag_with_ref: true
        tag_with_sha: false
        tags: latest,${{ env.CURR_TAG }}

   
   