name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    #- name: Build Docker images
      #run: docker-compose build
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: check Docker images
      run: docker images
   