name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  ONWER_ID: jonatan-bravo
jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build . --file install/nginx/Dockerfile --tag basermc1/nginx:$
    - name: Push the tagged Docker image
      run: docker push basermc1/nginx:$
    - name: Build the latest Docker image
      run: docker build . --file Dockerfile --tag basermc1/nginx:latest
    - name: Push the latest Docker image
      run: docker push basermc1/nginx:latest

   
    